from typing import Tuple, Any

class BaseJudge:
    """
    Abstract base class for environments that evaluate the Proposer's output.
    """
    
    def evaluate(self, output: str) -> Tuple[bool, float, str]:
        """
        Evaluates the provided output.
        
        Args:
            output (str): The code, strategy, or answer generated by the Proposer.
            
        Returns:
            Tuple[bool, float, str]: 
                - is_success (bool): True if the benchmark was met.
                - score (float): The numerical score (e.g., 0.85 for 85% win rate).
                - feedback (str): Detailed feedback/logs to pass to the Critic if it failed.
        """
        raise NotImplementedError("Subclasses must implement the evaluate method.")
